/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      keyframes: {
        zoomInOut: {
          '0%': { transform: 'scale(1)' },
          '1%': { transform: 'scale(1.01)' },
          '2%': { transform: 'scale(1.02)' },
          '3%': { transform: 'scale(1.03)' },
          '4%': { transform: 'scale(1.04)' },
          '5%': { transform: 'scale(1.05)' },
          '6%': { transform: 'scale(1.06)' },
          '7%': { transform: 'scale(1.07)' },
          '8%': { transform: 'scale(1.08)' },
          '9%': { transform: 'scale(1.09)' },
          '10%': { transform: 'scale(1.1)' },
          '11%': { transform: 'scale(1.11)' },
          '12%': { transform: 'scale(1.12)' },
          '13%': { transform: 'scale(1.13)' },
          '14%': { transform: 'scale(1.14)' },
          '15%': { transform: 'scale(1.15)' },
          '16%': { transform: 'scale(1.16)' },
          '17%': { transform: 'scale(1.17)' },
          '18%': { transform: 'scale(1.18)' },
          '19%': { transform: 'scale(1.19)' },
          '20%': { transform: 'scale(1.2)' },
          '21%': { transform: 'scale(1.21)' },
          '22%': { transform: 'scale(1.22)' },
          '23%': { transform: 'scale(1.23)' },
          '24%': { transform: 'scale(1.24)' },
          '25%': { transform: 'scale(1.25)' },
          '26%': { transform: 'scale(1.26)' },
          '27%': { transform: 'scale(1.27)' },
          '28%': { transform: 'scale(1.28)' },
          '29%': { transform: 'scale(1.29)' },
          '30%': { transform: 'scale(1.3)' },
          '31%': { transform: 'scale(1.31)' },
          '32%': { transform: 'scale(1.32)' },
          '33%': { transform: 'scale(1.33)' },
          '34%': { transform: 'scale(1.34)' },
          '35%': { transform: 'scale(1.35)' },
          '36%': { transform: 'scale(1.36)' },
          '37%': { transform: 'scale(1.37)' },
          '38%': { transform: 'scale(1.38)' },
          '39%': { transform: 'scale(1.39)' },
          '40%': { transform: 'scale(1.4)' },
          '41%': { transform: 'scale(1.41)' },
          '42%': { transform: 'scale(1.42)' },
          '43%': { transform: 'scale(1.43)' },
          '44%': { transform: 'scale(1.44)' },
          '45%': { transform: 'scale(1.45)' },
          '46%': { transform: 'scale(1.46)' },
          '47%': { transform: 'scale(1.47)' },
          '48%': { transform: 'scale(1.48)' },
          '49%': { transform: 'scale(1.49)' },
          '50%': { transform: 'scale(1.5)' },
          '51%': { transform: 'scale(1.49)' },
          '52%': { transform: 'scale(1.48)' },
          '53%': { transform: 'scale(1.47)' },
          '54%': { transform: 'scale(1.46)' },
          '55%': { transform: 'scale(1.45)' },
          '56%': { transform: 'scale(1.44)' },
          '57%': { transform: 'scale(1.43)' },
          '58%': { transform: 'scale(1.42)' },
          '59%': { transform: 'scale(1.41)' },
          '60%': { transform: 'scale(1.4)' },
          '61%': { transform: 'scale(1.39)' },
          '62%': { transform: 'scale(1.38)' },
          '63%': { transform: 'scale(1.37)' },
          '64%': { transform: 'scale(1.36)' },
          '65%': { transform: 'scale(1.35)' },
          '66%': { transform: 'scale(1.34)' },
          '67%': { transform: 'scale(1.33)' },
          '68%': { transform: 'scale(1.32)' },
          '69%': { transform: 'scale(1.31)' },
          '70%': { transform: 'scale(1.3)' },
          '71%': { transform: 'scale(1.29)' },
          '72%': { transform: 'scale(1.28)' },
          '73%': { transform: 'scale(1.27)' },
          '74%': { transform: 'scale(1.26)' },
          '75%': { transform: 'scale(1.25)' },
          '76%': { transform: 'scale(1.24)' },
          '77%': { transform: 'scale(1.23)' },
          '78%': { transform: 'scale(1.22)' },
          '79%': { transform: 'scale(1.21)' },
          '80%': { transform: 'scale(1.2)' },
          '81%': { transform: 'scale(1.19)' },
          '82%': { transform: 'scale(1.18)' },
          '83%': { transform: 'scale(1.17)' },
          '84%': { transform: 'scale(1.16)' },
          '85%': { transform: 'scale(1.15)' },
          '86%': { transform: 'scale(1.14)' },
          '87%': { transform: 'scale(1.13)' },
          '88%': { transform: 'scale(1.12)' },
          '89%': { transform: 'scale(1.11)' },
          '90%': { transform: 'scale(1.1)' },
          '91%': { transform: 'scale(1.09)' },
          '92%': { transform: 'scale(1.08)' },
          '93%': { transform: 'scale(1.07)' },
          '94%': { transform: 'scale(1.06)' },
          '95%': { transform: 'scale(1.05)' },
          '96%': { transform: 'scale(1.04)' },
          '97%': { transform: 'scale(1.03)' },
          '98%': { transform: 'scale(1.02)' },
          '99%': { transform: 'scale(1.01)' },
          '100%': { transform: 'scale(1)' },
        },
        slideIn: {
          "0%": { transform: "translateX(100%)" },
          "100%": { transform: "translateX(0)" },
        },
        fadeIn: {
          "0%": { opacity: 0.8 },
          "100%": { opacity: 1 },
        },
        spin: {
          from: {
            transform: 'rotate(0deg)',
          },
          to: {
            transform: 'rotate(360deg)',
          },
        },
      },
      animation: {
        blob: 'blob 7s infinite',
        zoomInOut: '1s zoomInOut 6s 1',
        "fade-in": "fadeIn 1s ease-in forwards",
        slideIn: "slideIn 2s ease-in-out",
        spin: "spin 1s linear infinite",
        spinOnce : "spin 1s linear",
        pulse: "pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite",
        bounce: "bounce 1s infinite",
        shake: "shake 0.5s cubic-bezier(.36,.07,.19,.97) infinite",
      },
    },
  },
  variants: {},
  plugins: [],
};